### ISSUE TITLE
Algorix logo

### ISSUE THREAD

**Issue by treehill05** [YTG2G3/algorix.io#1]
Replace app/favicon.ico and public/algorix_logo_light.png

**Comment by ryankwondev** [comment]
![algorix_logo_light](https://github.com/YTG2G3/algorix.io/assets/93381265/0420c162-ea8f-49e0-9db0-f1a5ed59d8e0)
![fabicon](https://github.com/YTG2G3/algorix.io/assets/93381265/a1a73bf2-9925-4e5f-8bac-7d838f6dbfdb)
![algorix](https://github.com/YTG2G3/algorix.io/assets/93381265/b9378d6a-d71e-427a-a4ea-92a3e9202b2c)

**Comment by ryankwondev** [comment]
[Archive.zip](https://github.com/YTG2G3/algorix.io/files/14358508/Archive.zip)
